# Generated by Django 2.2.1 on 2019-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='nofquestion',
            field=models.IntegerField(default=0),
        ),
    ]
