# Generated by Django 2.2.1 on 2019-07-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_userprofileinfo_nofquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct',
            field=models.CharField(max_length=1),
        ),
    ]
