# Generated by Django 2.2.1 on 2019-07-15 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_userprofileinfo_lastquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='lastQuestion',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 18, 11, 31, 958593, tzinfo=utc)),
        ),
    ]
